from Kernel.KernelStruct.bytecode_format import r
from Kernel.KernelStruct.system_functions import sc

method_1 = [
    [r['assign'], [r['reg'], 0, []], [r['concept_instance'], 1]],
    [r['for'], 0, [0], [r['system_call'], sc['max'], [[r['size'], [r['input'], 0]], [r['size'], [r['input'], 1]]]], 15],
    [r['if'], [r['system_call'], sc['and'],
               [[r['system_call'], sc['<'], [[r['iterator'], 0], [r['size'], [r['input'], 0]]]],
                [r['system_call'], sc['<'], [[r['iterator'], 0], [r['size'], [r['input'], 1]]]]]], 3],
    [r['assign'], [r['reg'], 1, [[r['iterator'], 0]]],
     [r['call'], 2, [[r['call'], 3, [[r['at_reverse'], [r['input'], 0], [r['iterator'], 0]]]],
      [r['call'], 3, [[r['at_reverse'], [r['input'], 1], [r['iterator'], 0]]]]]]],
    [r['else_if'], [r['system_call'], sc['and'],
                    [[r['system_call'], sc['<'], [[r['iterator'], 0], [r['size'], [r['input'], 0]]]],
                     [r['system_call'], sc['>='], [[r['iterator'], 0], [r['size'], [r['input'], 1]]]]]], 5],
    [r['assign'], [r['reg'], 1, [[r['iterator'], 0]]], [r['call'], 3, [[r['at_reverse'], [r['input'], 0], [r['iterator'], 0]]]]],
    [r['else_if'], [r['system_call'], sc['and'],
                    [[r['system_call'], sc['>='], [[r['iterator'], 0], [r['size'], [r['input'], 0]]]],
                     [r['system_call'], sc['<'], [[r['iterator'], 0], [r['size'], [r['input'], 1]]]]]], 7],
    [r['assign'], [r['reg'], 1, [[r['iterator'], 0]]], [r['call'], 3, [[r['at_reverse'], [r['input'], 1], [r['iterator'], 0]]]]],
    [r['if'], [r['system_call'], sc['=='], [[r['iterator'], 0], [0]]], 9],
    [r['assign'], [r['reg'], 2, [[r['iterator'], 0]]], [r['reg'], 1, [[r['iterator'], 0]]]],
    [r['if'], [r['system_call'], sc['and'], [[r['system_call'], sc['>='], [[r['iterator'], 0], [1]]],
                                             [r['system_call'], sc['>='], [[r['size'], [r['reg'], 2,
                                                                                        [[r['system_call'], sc['offset'],
                                                                                         [[r['iterator'], 0], [-1]]]]]],
                                                                           [2]]]]], 11],
    [r['assign'], [r['reg'], 2, [[r['iterator'], 0]]], [r['call'], 2, [[r['reg'], 1, [[r['iterator'], 0]]],
                                                                       [r['call'], 3, [[r['at_reverse'], [r['reg'], 2, [[
                                                                           r['system_call'], sc['offset'],
                                                                           [[r['iterator'], 0], [-1]]]]], [1]]]]]]],
    [r['else'], 13],
    [r['assign'], [r['reg'], 2, [[r['iterator'], 0]]], [r['reg'], 1, [[r['iterator'], 0]]]],
    [r['delete'], 1, [[r['iterator'], 0]]],
    [r['assign'], [r['at_reverse'], [r['reg'], 0, []], [r['iterator'], 0]],
     [r['at_reverse'], [r['reg'], 2, [[r['iterator'], 0]]], [0]]],
    [r['if'], [r['system_call'], sc['>='], [[r['size'], [r['reg'], 2, [[r['system_call'], sc['offset'], [
        [r['system_call'], sc['max'], [[r['size'], [r['input'], 0]], [r['size'], [r['input'], 1]]]], [-1]]]]]], [2]]],
     17],
    [r['assign'], [r['at_reverse'], [r['reg'], 0, []],
                   [r['system_call'], sc['max'], [[r['size'], [r['input'], 0]], [r['size'], [r['input'], 1]]]]],
     [r['at_reverse'],
      [r['reg'], 2, [[r['system_call'], sc['offset'], [[r['system_call'], sc['max'], [[r['size'], [r['input'], 0]], [r['size'], [r['input'], 1]]]], [-1]]]]],
      [1]]],
    [r['delete'], 2, []],
    [r['return'], [r['reg'], 0, []]]
]
temp = [6, 8, [[20, [1, 0]], [20, [1, 1]]]]
method_2 = [
    [r['assign'], [r['reg'], 0, []], [r['concept_instance'], 1]],

    [r['if'],      [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 2],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 4],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 6],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 8],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 10],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 12],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 14],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 16],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 18],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 100]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 20],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 22],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 24],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 26],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 28],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 30],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 32],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 34],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 36],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 38],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 101]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 41],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 43],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 45],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 47],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 49],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 51],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 53],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 55],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 57],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 60],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 102]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 63],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 65],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 67],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 69],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 71],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 73],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 75],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 77],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 80],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 83],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 103]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 86],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 88],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 90],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 92],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 94],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 96],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 98],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 101],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 104],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 107],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 104]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 110],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 112],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 114],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 116],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 118],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 120],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 123],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 126],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 129],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 132],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 105]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 135],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 137],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 139],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 141],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 143],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 146],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 149],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 152],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 155],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 158],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 106]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 161],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 163],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 165],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 167],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 170],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 173],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 176],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 179],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 182],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 185],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 107]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 188],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 190],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 108]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 192],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 195],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 198],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 201],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 204],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 207],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 210],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 213],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 108]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 216],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 100]]]]], 218],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 109]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 101]]]]], 221],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 100]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 102]]]]], 224],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 101]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 103]]]]], 227],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 102]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 104]]]]], 230],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 103]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 105]]]]], 233],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 104]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 106]]]]], 236],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 105]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 107]]]]], 239],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 106]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 108]]]]], 242],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 107]],
    [r['else_if'], [r['system_call'], sc['and'], [[r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 0], [0]], [r['concept_instance'], 109]]], [r['system_call'], sc['=='], [[r['at_reverse'], [r['input'], 1], [0]], [r['concept_instance'], 109]]]]], 245],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['concept_instance'], 101]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [1]], [r['concept_instance'], 108]],

    [r['return'], [r['reg'], 0, []]]
]

method_3 = [
    [r['assign'], [r['reg'], 0, []], [r['concept_instance'], 1]],
    [r['assign'], [r['at'], [r['reg'], 0, []], [0]], [r['input'], 0]],
    [r['return'], [r['reg'], 0, []]]
]
